// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

/*
 * Interface for the solidity verifier generated by snarkjs
 */
interface IVerifier {
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[4] memory input
    ) external view returns (bool);
}

contract ConcealedHand {
    IVerifier verifierContract =
        IVerifier(0x5FbDB2315678afecb367f032d93F642f64180aa3);
}
